version: '3.8'

services:
  pgvector:
    image: pgvector/pgvector:pg16
    container_name: pgvector_db_1
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin@123
      POSTGRES_DB: my_db
    ports:
      - "5433:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data
    restart: unless-stopped

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: genai_api
    env_file:
      - .env
    environment:
      - FLASK_ENV=production
      - POSTGRES_HOST=pgvector
      - POSTGRES_PORT=5432
      - GOOGLE_API_KEY=API_KEY
    ports:
      - "5000:5000"
    volumes:
      - ./api/uploads:/app/uploads
      - ./api/kb_info:/app/kb_info
    depends_on:
      - pgvector
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: genai_frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/local/apache2/htdocs/:ro
    restart: unless-stopped

volumes:
  pgvector_data:
  api_uploads:
  api_kb_info: